### PR TITLE
Changes the Json serializer logic....

### LINKED ISSUE #351: API no more working.
http://www.mix-it.fr/article/40/wanna-hack-mix-it-

Any non empty JSON response lead to crash...
Since migration to CloudFoundry?

### PR DESCRIPTION
**Pull request by javamind**
We now use only one Serializer adapter for one type
Fix #351

### CODE REVIEW

File: app/controllers/api/ApiMembers.java [hunk 1]
```diff
@@ -1,50 +1,51 @@
...
+    private static JsonSerializer STAFF_SERIALIZER = new StaffJsonSerializer(false);
+    private static JsonSerializer MEMBER_SERIALIZER = new MemberJsonSerializer(false);
+    private static JsonSerializer TALK_SERIALIZER = new TalkJsonSerializer(true);
+
 
     public static void speakers(boolean details) {
         List<Member> speakers = Talk.findAllSpeakersOn(ConferenceEvent.CURRENT);
-        renderJSON(speakers, getSerializers(details));
+        for (Member m : speakers) {
+            m.sessions = null;
```
Comment (clacote) [inline app/controllers/api/ApiMembers.java]: Whaaat? What is the point of exposing speakers if they don't have their sessions as data?

File: app/controllers/api/JsonpController.java [hunk 2]
```diff
@@ -17,33 +18,21 @@
...
-        if (callback != null) {
-            Controller.renderJSON(String.format(CALLBACK_FORMAT, callback, str));
-        } else {
-            Controller.renderJSON(str);
-        }
-    }
-
-    @Util
-    protected static void renderJSON(Object o, JsonSerializer<?>... adapters) {
+    protected static <T> void renderJSON(Class<T> type, T o, JsonSerializer<T> adapter) {
```
Comment (clacote) [inline app/controllers/api/JsonpController.java]: Hmmm. You just broke the common Play controller signatures. But that's OK.

File: app/models/Member.java [hunk 3]
```diff
@@ -144,6 +145,7 @@
     public Set<Badge> badges = EnumSet.noneOf(Badge.class);
 
     @ManyToMany(mappedBy="speakers")
+    @NoExposeExclusionStrategy.NoExpose
```
Comment (clacote) [inline app/models/Member.java]: Isn't this redundant with setting this attribute to null when exposed to JSON API?

File: app/controllers/api/ApiMembers.java (hunk 1 above)
Comment (clacote) [inline app/controllers/api/ApiMembers.java]: Also, modifying an entity is scary and dirty, even if you are lucky enough that Play doesn't automatically persist changes on managed entity (unlike pure Hibernate).

**Comment by clacote** [comment]
You have lost the usage of `details` boolean parameter.

File: app/models/Member.java (hunk 3 above)
Comment (javamind) [inline app/models/Member.java]: It was my first fix. I iterate on all the members before the serialization and I set the null value for "sessions" properties. But it's dangerous in a context with Hibernate. If you are in a session and if yours objects are attached you can delete all the relations

File: app/controllers/api/JsonpController.java (hunk 2 above)
Comment (javamind) [inline app/controllers/api/JsonpController.java]: Play,  it stinks... :smile:

File: app/controllers/api/ApiMembers.java (hunk 1 above)
Comment (javamind) [inline app/controllers/api/ApiMembers.java]: Oups the iteration should be deleted

**Comment by javamind** [comment]
@clacote ready for a new code review ?

File: app/models/Member.java (hunk 3 above)
Comment (clacote) [inline app/models/Member.java]: And is this stil useful? Your explicit serializers probably don't use it.

File: app/controllers/api/JsonpController.java (hunk 2 above)
Comment (clacote) [inline app/controllers/api/JsonpController.java]: Is it the original code that causes the bug? If not, it could be better to restore it, to fall back into common Play's controllers signature. That way, our `ApiXxx` controllers could inherit from `JsonpController` as of now, or Play's `Controller` as originally, without having to refactor code.

Comment (javamind) [inline app/controllers/api/JsonpController.java]: I don't understand your remark. 
Our `Apixxx` need our own `JsonpController` because they have to 
1) customize the serialisation 
2) use our own `GsonBuilder` to be able to exclude some properties like `sessions` in the bean `Member`

File: app/models/Member.java (hunk 3 above)
Comment (javamind) [inline app/models/Member.java]: Yes without this exclusion the `GsonBuilder` tries to read these sessions even if they are not present in the final json

File: app/controllers/api/JsonpController.java (hunk 2 above)
Comment (clacote) [inline app/controllers/api/JsonpController.java]: 1) customization was already done in original JsonpController code.
2) exclusion is probably not made through the use of your @NoExpose annotation, but because the custom serializers do what they have to, breaking circular references.

All I want to say is that the original code in JsonpController class respects signature of Play's `Controller` class. So if there is no use of breaking these signatures, it's better not to.

Comment (clacote) [inline app/controllers/api/JsonpController.java]: Also, JsonpController was not done to accept customization (original Play's `Controller` can), but to expose a JSONP-enabled API. If it's the only way and place to fix the bug, OK. But if it's not, it's better to not break compatibility.

Comment (javamind) [inline app/controllers/api/JsonpController.java]: I made a lot of tests to find a solution. If you have a better solution, I am interested. I didn't find how to customize the `GsonBuilder` used by Play.
After the custom serializers didn't break circular references. So we have to find another solution. This one is cheaper than change Gson to Jackson

**Comment by javamind** [comment]
I tested your proposition @clacote  on localhost (http://localhost:9000/api/members)  ==> failed
```
 Execution exception : 
 IllegalStateException occured : circular reference error Offending field: links Offending object:   
 preserveType: true, type: class models.Member, obj: Aumzqnsyhdxnlfkavrdkekbtszmp
 In /app/controllers/api/JsonpController.java (around line 35)
```

**Comment by clacote** [comment]
This PR is not mergeable: your branch needs to be rebased onto master. There will be conflicts.
```
git fetch upstream master
git rebase upstream/master
````

**Comment by clacote** [comment]
you're lucky, conflicts are easy to merge: only imports in `Session.java` (I tried to rebase your branch).

**Comment by javamind** [comment]
Rebase done

**Comment by clacote** [comment]
That works \o/ : http://www.mix-it.fr/api/members/sponsors?details=true
